[package]
name = "nbodysim"
version = "0.1.0"
authors = ["timokoesters <timo@koesters.xyz>"]
edition = "2018"

[dependencies]
winit = "0.20.0"
wgpu = "0.4.0"
glsl-to-spirv = "0.1.7"
cgmath = "0.17.0"
raw-window-handle = "0.3.3"
rand = "0.7.2"
rand_distr = "0.2.2"
